### ISSUE TITLE
.husky removal from git repo

### ISSUE THREAD

**Issue by RamanSharma100** [SMAKSS/react-scroll-direction#169]
remove .husky from github its giving issues while installing

**Comment by RamanSharma100** [comment]
remove .husky from github its giving issues while installing

**Comment by SMAKSS** [comment]
@RamanSharma100 Hi, thank you for opening this issue. Can you specify what is the exact error and a way to reproduce it?

**Comment by SMAKSS** [comment]
> > @RamanSharma100 Hi, thank you for opening this issue. Can you specify what is the exact error and a way to reproduce it?
> 
> The error is that, you don't have husky installed so it's not getting installed.

OK, thank you. I will try to reproduce it and see what is the issue.

**Comment by SMAKSS** [comment]
This issue is fixed in the [v3.0.2](https://github.com/SMAKSS/react-scroll-direction/releases/tag/v3.0.2). Thank you, @RamanSharma100, for reporting it. I will then close the issue.
