### ISSUE TITLE
ScollDir is always down

### ISSUE THREAD

**Issue by astralarya** [SMAKSS/react-scroll-direction#258]
# Brief Description
The scroll direction hook always returns down, even when scrolling up.

## Environment

- `@smakss/react-scroll-direction` version: 4.04
- Framework version: react
- `node.js` version: 20.8.0
- `yarn` version: 1.22.19

## Code Snippet

```javascript
export default function Example() {
  const { scrollDir } = useDetectScroll();

  console.log(scrollDir);

  return "ababa";
}
```

## Steps to Reproduce

Scroll up and down

## Expected Behavior

Scrolling up returns up.

## Actual Behavior

Events always return direction as down.

**Comment by SMAKSS** [comment]
Hello! Apologies for the delayed reply, and thank you 🙏 for bringing this to our attention. I'm on it and will investigate the issue immediately.

**Comment by SMAKSS** [comment]
Hi @astralarya,

Thanks for bringing this to my attention. Despite testing on Chrome, Firefox, and Safari with the same Node.js version, the issue couldn't be replicated on my end. To dive deeper and find a solution, could you please provide the following details?

1. **Browser and Version:**
2. **Operating System:**
3. **Bundler** If any
4. **Console Errors/Warnings:** If any.
5. **Specific Conditions:** Under which the issue seems more pronounced, if applicable.
6. **Visuals:** A video or screenshots capturing the issue, if possible.

Your further insights will be crucial for me to identify and address the problem effectively. I appreciate your cooperation and patience.

Thank you!

**Comment by KubaZachacz** [comment]
Hey @SMAKSS 
It's really looks like it might show 'Still' at start and only down 'Down' later
Here's my: [codesanbox](https://codesandbox.io/p/github/Bhanu1776/Nextjs14-Starter-Template/csb-vlkydn/draft/amazing-tdd?file=%2Fapp%2Fpage.tsx%3A11%2C1&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clul110u80007356hojxzwfp4%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clul110u80002356hs9enb856%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clul110u80004356hppgjaouk%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clul110u80006356hgvescqp2%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clul110u80002356hs9enb856%2522%253A%257B%2522id%2522%253A%2522clul110u80002356hs9enb856%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clul110u80006356hgvescqp2%2522%253A%257B%2522id%2522%253A%2522clul110u80006356hgvescqp2%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3001%252C%2522id%2522%253A%2522clul16wn100bi356i30fmreah%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clul16wn100bi356i30fmreah%2522%257D%252C%2522clul110u80004356hppgjaouk%2522%253A%257B%2522id%2522%253A%2522clul110u80004356hppgjaouk%2522%252C%2522activeTabId%2522%253A%2522clul16j1h007o356ibyqrsz0m%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522clul16j1h007o356ibyqrsz0m%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522id%2522%253A%2522clul17nr200g2356i0jz993hc%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clul17no8002bdifea30rdinl%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D) I hope it will work enough to show the bug. 

In general in my project and sandbox it's  Node 20+ and Next.Js 14+ with appDir

**Comment by SMAKSS** [comment]
Thanks to @astralarya and @KubaZachacz for your support and contributions! I've deployed a fix. Please update to the [latest version](https://www.npmjs.com/package/@smakss/react-scroll-direction) and check if it resolves the issue.

Looking forward to your feedback!
