### ISSUE TITLE
Feature request: allow specifying a custom scrollable element to track

### ISSUE THREAD

**Issue by EvgenyOrekhov** [SMAKSS/react-scroll-direction#263]
## Problem Description

Right now react-scroll-direction can track only `window` scroll.
It would be great if it could track scroll for any custom scrollable element.

## Suggested Solution

Maybe make it accept a ref?

```js
const ref = useRef();
const { scrollDir } = useDetectScroll({ ref });
```

**Comment by SMAKSS** [comment]
Hi @EvgenyOrekhov, thanks for your feature suggestion! I’ll aim to include it in the upcoming major release.
